/**
 * Generates a high-fidelity SAP Functional Specification Document (FSD) in Google Docs.
 * Uses the Google Docs API v1 (authenticated via OAuth2).
 * @param {Object} roadmap - The technical roadmap from Aether.
 * @param {string} accessToken - The OAuth2 access token.
 */
export const generateFSD = async (roadmap, accessToken) => {
  if (!roadmap || !accessToken) {
    throw new Error("Neural Link required for FSD Generation.");
  }

  try {
    // 1. Create the Document
    const createUrl = 'https://docs.googleapis.com/v1/documents';
    const createResponse = await fetch(createUrl, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        title: `SDAssist_FSD_${roadmap.scenario_type}_${new Date().getTime()}`
      })
    });

    if (!createResponse.ok) {
      const err = await createResponse.json();
      throw new Error(err.error?.message || "Google Docs creation failed.");
    }

    const doc = await createResponse.json();
    const documentId = doc.documentId;

    // 2. Prepare content
    const stepsText = roadmap.configuration_roadmap?.map(s => `Step: ${s.step}\nT-Code: ${s.tcode}\nDetail: ${s.description}\n\n`).join('') || 'No steps provided.';
    const content = `
SAP S/4HANA FUNCTIONAL SPECIFICATION DOCUMENT
-----------------------------------------------
Generated by SDAssist Aether (Neural OS v5.1)
Scenario: ${roadmap.scenario_type}
Timestamp: ${new Date().toISOString()}

EXECUTIVE SUMMARY:
This document outlines the technical configuration steps for the ${roadmap.scenario_type} requirement.

TECHNICAL BLUEPRINT:
${stepsText}

ARCHITECTURAL WARNINGS:
${roadmap.warnings?.join('\n') || 'None'}

End of Document.
    `;

    // 3. Populate completion (Batch Update)
    const updateUrl = `https://docs.googleapis.com/v1/documents/${documentId}:batchUpdate`;
    const updateResponse = await fetch(updateUrl, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        requests: [
          {
            insertText: {
              location: { index: 1 },
              text: content
            }
          }
        ]
      })
    });

    if (!updateResponse.ok) {
      const err = await updateResponse.json();
      throw new Error(err.error?.message || "Document population failed.");
    }

    return { success: true, docUrl: `https://docs.google.com/documents/d/${documentId}/edit` };
  } catch (error) {
    console.error("FSD Generation Error:", error);
    throw error;
  }
};
