import React, { useMemo } from 'react';
import { createPortal } from 'react-dom';
import { FileText, Download, X, Copy, Check } from 'lucide-react';

const FsdViewer = ({ roadmap, onClose }) => {
  const [copied, setCopied] = React.useState(false);

  const fsdContent = useMemo(() => {
    if (!roadmap) return 'No roadmap data available.';
    const stepsText = roadmap.configuration_roadmap?.map(s => `[STEP ${s.step || ''}]\nT-Code: ${s.tcode || 'N/A'}\nDescription: ${s.description || 'N/A'}\n\n`).join('') || 'No steps provided.';
    return `================================================
SAP S/4HANA FUNCTIONAL SPECIFICATION DOCUMENT
================================================
Generated by: SDAssist Aether (Neural OS v5.1)
Scenario Scope: ${roadmap.scenario_type || 'General'}
Timestamp: ${new Date().toISOString()}

------------------------------------------------
EXECUTIVE SUMMARY
------------------------------------------------
This document outlines the technical configuration steps for the ${roadmap.scenario_type || 'General'} requirement. These steps are strictly validated against SAP S/4HANA best practices.

------------------------------------------------
TECHNICAL BLUEPRINT (CONFIGURATION STEPS)
------------------------------------------------
${stepsText}
------------------------------------------------
ARCHITECTURAL WARNINGS
------------------------------------------------
${roadmap.warnings?.map(w => `- ${w}`).join('\n') || 'No critical warnings detected.'}

================================================
[END OF DOCUMENT]
================================================`;
  }, [roadmap]);

  const handleDownload = () => {
    const blob = new Blob([fsdContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SDAssist_FSD_${roadmap?.scenario_type || 'Draft'}_${new Date().getTime()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(fsdContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return createPortal(
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-8 bg-background/80 backdrop-blur-sm animate-in fade-in duration-300">
      <div className="glass-panel w-full max-w-4xl h-full max-h-[85vh] rounded-2xl border border-outline-variant/20 shadow-2xl relative flex flex-col">
        {/* Header */}
        <header className="p-6 border-b border-outline-variant/10 flex items-center justify-between bg-surface-container/50 rounded-t-2xl shrink-0">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary border border-primary/20">
              <FileText size={20} />
            </div>
            <div>
              <h3 className="font-headline text-lg font-bold tracking-tight text-on-surface">Functional Specification</h3>
              <p className="text-[10px] text-primary font-bold uppercase tracking-[0.2em]">{roadmap?.scenario_type || 'Draft'} • .TXT Viewer</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button 
              onClick={handleCopy}
              aria-label="Copy to Clipboard"
              className="px-4 py-2 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface text-xs font-bold transition-all flex items-center gap-2 border border-outline-variant/10"
            >
              {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} className="text-on-surface-variant" />}
              {copied ? 'Copied!' : 'Copy'}
            </button>
            <button 
              onClick={handleDownload}
              aria-label="Download TXT File"
              className="px-4 py-2 rounded-lg bg-primary hover:bg-primary-dim text-on-primary text-xs font-bold transition-all flex items-center gap-2"
            >
              <Download size={14} />
              Download .txt
            </button>
            <div className="w-px h-6 bg-outline-variant/20 mx-2"></div>
            <button 
              onClick={onClose}
              aria-label="Close FSD Viewer"
              className="p-2 text-on-surface-variant hover:text-error transition-colors bg-surface-container rounded-lg hover:bg-error/10"
            >
              <X size={20} />
            </button>
          </div>
        </header>

        {/* Text Content */}
        <div className="flex-1 overflow-auto p-6 bg-[#000000]/40 font-mono text-sm leading-relaxed text-on-surface-variant/90 custom-scrollbar whitespace-pre-wrap rounded-b-2xl">
          {fsdContent}
        </div>
      </div>
    </div>,
    document.body
  );
};

export default FsdViewer;
