import React, { useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { FileText, Download, X, Copy, Check, Code } from 'lucide-react';

const FsdViewer = ({ roadmap, onClose }) => {
  const [copied, setCopied] = useState(false);
  const [viewMode, setViewMode] = useState('fsd'); // 'fsd' or 'abap'

  const fsdContent = useMemo(() => {
    if (!roadmap) return 'No roadmap data available.';
    const stepsText = roadmap.configuration_roadmap?.map(s => `[STEP ${s.step || ''}]\nT-Code: ${s.tcode || 'N/A'}\nDescription: ${s.description || 'N/A'}\n\n`).join('') || 'No steps provided.';
    return `================================================
SAP S/4HANA FUNCTIONAL SPECIFICATION DOCUMENT
================================================
Generated by: SDAssist Aether (Neural OS v5.1)
Scenario Scope: ${roadmap.scenario_type || 'General'}
Timestamp: ${new Date().toISOString()}

------------------------------------------------
EXECUTIVE SUMMARY
------------------------------------------------
This document outlines the technical configuration steps for the ${roadmap.scenario_type || 'General'} requirement. These steps are strictly validated against SAP S/4HANA best practices.

------------------------------------------------
TECHNICAL BLUEPRINT (CONFIGURATION STEPS)
------------------------------------------------
${stepsText}
------------------------------------------------
ARCHITECTURAL WARNINGS
------------------------------------------------
${roadmap.warnings?.map(w => `- ${w}`).join('\n') || 'No critical warnings detected.'}

================================================
[END OF DOCUMENT]
================================================`;
  }, [roadmap]);

  const abapContent = useMemo(() => {
    if (!roadmap) return '* No ABAP specification generated.';
    
    let bapiName = 'BAPI_SALESORDER_CREATEFROMDAT2';
    if (roadmap.scenario_type?.toLowerCase().includes('mm') || roadmap.scenario_type?.toLowerCase().includes('material')) {
      bapiName = 'BAPI_MATERIAL_SAVEDATA';
    } else if (roadmap.scenario_type?.toLowerCase().includes('fico') || roadmap.scenario_type?.toLowerCase().includes('finance')) {
      bapiName = 'BAPI_ACC_DOCUMENT_POST';
    } else if (roadmap.scenario_type?.toLowerCase().includes('pricing')) {
      bapiName = 'BAPI_PRICES_CONDITIONS';
    }

    const stepsComments = roadmap.configuration_roadmap?.map(s => `* [STEP ${s.step || ''}] ${s.description || ''}`).join('\n') || '* No steps provided.';
    const progName = roadmap.scenario_type?.replace(/[^A-Za-z0-9_]/g, '').toUpperCase().substring(0, 15) || 'DRAFT';

    return `*&---------------------------------------------------------------------*
*& Report  Z_AETHER_${progName}
*& Description: Auto-Generated ABAP Wrapper for ${roadmap.scenario_type || 'General'}
*&---------------------------------------------------------------------*
REPORT Z_AETHER_${progName}.

* Functional Configuration Steps Embedded:
${stepsComments}

DATA: lt_return TYPE TABLE OF bapiret2,
      ls_return TYPE bapiret2.

* Primary BAPI determined by Aether Neural Engine
CALL FUNCTION '${bapiName}'
  EXPORTING
    " TO DO: Map exporting parameters based on FSD Master Data
  TABLES
    return = lt_return.

* Error Handling Loop
LOOP AT lt_return INTO ls_return WHERE type = 'E' OR type = 'A'.
  WRITE: / 'Error:', ls_return-message.
ENDLOOP.

IF sy-subrc = 0.
  CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
    EXPORTING
      wait = 'X'.
  WRITE: / 'Successfully processed ${roadmap.scenario_type || 'scenario'}.'.
ENDIF.
`;
  }, [roadmap]);

  const jiraContent = useMemo(() => {
    if (!roadmap) return '* No Jira EPIC specification generated.';
    
    const stories = roadmap.configuration_roadmap?.map((s, i) => `
### Story ${i + 1}: ${s.step || ''}
*As a* SAP consultant, 
*I need to* execute T-Code [ ${s.tcode || 'N/A'} ], 
*So that* ${s.description || 'N/A'}

**Acceptance Criteria:**
- [x] Configuration saved to Transport Request.
- [x] Successfully tested in Dev Environment.
`).join('') || '* No stories provided.';

    return `================================================
JIRA EPIC: S/4HANA ${roadmap.scenario_type || 'General'} Configuration
================================================
Status: To Do
Priority: High
Assignee: Aether Agent 

**Background:** 
Technical enablement required for the "${roadmap.scenario_type}" workflow. 
Below are the individual User Stories auto-generated to track development.
------------------------------------------------
${stories}
================================================`;
  }, [roadmap]);

  const uatContent = useMemo(() => {
    if (!roadmap) return '* No UAT Test Scripts generated.';
    const rows = roadmap.configuration_roadmap?.map((s, i) => 
`| ${String(i + 1).padStart(2, '0')} | Execute T-Code ${s.tcode || 'N/A'} | Validate ${s.step || ''} | Pass / Fail |`
    ).join('\n') || '| -- | No steps provided | -- | -- |';

    return `================================================
UAT TEST SCRIPT: ${roadmap.scenario_type || 'General'}
================================================

| ID | Action (Test Step) | Expected Result | Status |
|----|--------------------|-----------------|--------|
${rows}

**Tester Sign-Off:** ___________________________  **Date:** _______________
`;
  }, [roadmap]);

  const ltmcContent = useMemo(() => {
    if (!roadmap) return '* No Master Data views generated.';
    const custViews = roadmap.master_data?.customer_views?.join(', ') || 'N/A';
    const matViews = roadmap.master_data?.material_views?.join(', ') || 'N/A';

    return `================================================
LTMC / MIGRATION COCKPIT SCHEMA: ${roadmap.scenario_type || 'General'}
================================================
* This schema defines the mandatory load sequences for Master Data objects.

MIGRATION OBJECT: CUSTOMER MASTER
------------------------------------------------
Mandatory Views Required: 
${custViews}

CSV TEMPLATE STRUCTURE (Header Row):
KUNNR, BUKRS, VKORG, VTWEG, SPART, NAME1, LAND1

MIGRATION OBJECT: MATERIAL MASTER
------------------------------------------------
Mandatory Views Required: 
${matViews}

CSV TEMPLATE STRUCTURE (Header Row):
MATNR, MTART, MBRSH, MEINS, VKORG, VTWEG
================================================`;
  }, [roadmap]);

  const activeContent = viewMode === 'fsd' ? fsdContent :
                        viewMode === 'abap' ? abapContent :
                        viewMode === 'jira' ? jiraContent :
                        viewMode === 'uat' ? uatContent :
                        ltmcContent;

  const handleDownload = () => {
    const blob = new Blob([activeContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    let ext = 'txt';
    if (viewMode === 'abap') ext = 'abap';
    if (viewMode === 'jira' || viewMode === 'uat' || viewMode === 'ltmc') ext = 'md';
    
    link.download = `SDAssist_${viewMode.toUpperCase()}_${roadmap?.scenario_type || 'Draft'}_${new Date().getTime()}.${ext}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(activeContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return createPortal(
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-8 bg-background/80 backdrop-blur-sm animate-in fade-in duration-300">
      <div className="glass-panel w-full max-w-4xl h-full max-h-[85vh] rounded-2xl border border-outline-variant/20 shadow-2xl relative flex flex-col">
        {/* Header */}
        <header className="p-6 border-b border-outline-variant/10 flex items-center justify-between bg-surface-container/50 rounded-t-2xl shrink-0">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary border border-primary/20">
              {viewMode === 'fsd' ? <FileText size={20} /> : <Code size={20} />}
            </div>
            <div>
              <h3 className="font-headline text-lg font-bold tracking-tight text-on-surface">
                {viewMode === 'fsd' ? 'Functional Specification' : 
                 viewMode === 'abap' ? 'ABAP Technical Spec' : 
                 viewMode === 'jira' ? 'Agile DevOps Epic' :
                 viewMode === 'uat' ? 'UAT Test Scripts' :
                 'Data Migration Schema'}
              </h3>
              <div className="flex mt-1 bg-surface-container rounded-md p-0.5 border border-outline-variant/10 w-fit flex-wrap gap-1">
                <button onClick={() => setViewMode('fsd')} className={`px-3 py-1 rounded text-[10px] font-bold uppercase tracking-widest transition-all ${viewMode === 'fsd' ? 'bg-primary text-on-primary' : 'text-on-surface-variant hover:text-on-surface'}`}>FSD</button>
                <button onClick={() => setViewMode('abap')} className={`px-3 py-1 rounded text-[10px] font-bold uppercase tracking-widest transition-all ${viewMode === 'abap' ? 'bg-secondary text-on-secondary' : 'text-on-surface-variant hover:text-on-surface'}`}>ABAP Wrapper</button>
                <button onClick={() => setViewMode('jira')} className={`px-3 py-1 rounded text-[10px] font-bold uppercase tracking-widest transition-all ${viewMode === 'jira' ? 'bg-blue-500 text-white' : 'text-on-surface-variant hover:text-on-surface'}`}>Jira Epic</button>
                <button onClick={() => setViewMode('uat')} className={`px-3 py-1 rounded text-[10px] font-bold uppercase tracking-widest transition-all ${viewMode === 'uat' ? 'bg-orange-500 text-white' : 'text-on-surface-variant hover:text-on-surface'}`}>UAT</button>
                <button onClick={() => setViewMode('ltmc')} className={`px-3 py-1 rounded text-[10px] font-bold uppercase tracking-widest transition-all ${viewMode === 'ltmc' ? 'bg-green-500 text-white' : 'text-on-surface-variant hover:text-on-surface'}`}>LTMC</button>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button 
              onClick={handleCopy}
              aria-label="Copy to Clipboard"
              className="px-4 py-2 rounded-lg bg-surface-container hover:bg-surface-container-high text-on-surface text-xs font-bold transition-all flex items-center gap-2 border border-outline-variant/10"
            >
              {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} className="text-on-surface-variant" />}
              {copied ? 'Copied!' : 'Copy'}
            </button>
            <button 
              onClick={handleDownload}
              aria-label={`Download ${viewMode.toUpperCase()} File`}
              className="px-4 py-2 rounded-lg bg-primary hover:bg-primary-dim text-on-primary text-xs font-bold transition-all flex items-center gap-2"
            >
              <Download size={14} />
              Download .{viewMode === 'fsd' ? 'txt' : viewMode === 'abap' ? 'abap' : 'md'}
            </button>
            <div className="w-px h-6 bg-outline-variant/20 mx-2"></div>
            <button 
              onClick={onClose}
              aria-label="Close FSD Viewer"
              className="p-2 text-on-surface-variant hover:text-error transition-colors bg-surface-container rounded-lg hover:bg-error/10"
            >
              <X size={20} />
            </button>
          </div>
        </header>

        {/* Text Content */}
        <div className="flex-1 overflow-auto p-6 bg-[#000000]/40 font-mono text-sm leading-relaxed text-on-surface-variant/90 custom-scrollbar whitespace-pre-wrap rounded-b-2xl">
          {activeContent}
        </div>
      </div>
    </div>,
    document.body
  );
};

export default FsdViewer;
